### ISSUE TITLE
Let's quickly setup a minimalist Parcel/TensorFlow starter kit

### ISSUE THREAD

**Issue by labofoz** [labofoz/vue-parcel-tensorflow#1]
**Excerpt from my Dailies**: https://labofoz.com/t/2019-03-24-tensorflow-js-vue-parcel-glitch-starter/19/2

---

So I've been having a lot of fun with tensorflow js and today I want to build a tensorflow Vue Parcel Glitch Starter, which is made  up of:

- **A Parcel environment on Glitch**. This is so that people can make use of the Glitch community help features when they get stuck. You can also embed them!
- **Use Vue to create a starter**. The starter is so that people can create their models and then use them and write about them all in the same repository (ps Google's speech-to-text is really really good!)

It should take me no more than 3 hours to do this, and I can use the lessons on Udacity as a way to guide the development

---

## Tasks
- [ ] Setup a `src/index.pug`
- [ ] Import `app.js`, which requires TensorFlow with [the load/create technique](https://labofoz.com/t/2019-03-23-collecting-my-old-projects/16/2?u=labofoz)
- [ ] Create a simple starter model to learn the Celsius to Fahrenheit formula
- [ ] Visualize model
- [ ] Visualize loss
- [ ] Add fields for inputs
- [ ] Visualize outputs

## Publish
- [ ] Announce on Twitter
- [ ] Create Medium post and submit to Glitch
- [ ] Share with TensorFlow community
- [ ] Embed on Labofoz.com
